### ISSUE TITLE
mocha: command not found

### ISSUE THREAD

**Issue by haruelrovix** [sudoak/askak#1]
Hi @sudoak 👋 ,

I'm Havit from AskSteve / AdaKerja.

I cloned your branch but getting an error when I tried to run `yarn test`.

```
➜  askak git:(master) ✗ yarn test
yarn run v1.16.0
$ mocha --timeout 10000
/bin/sh: mocha: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I did installing dependencies by running `yarn` previously.

1. What's wrong here?
2. Could you please update your repository to solve this issue?

Best Regards,
-Havit

**Comment by sudoak** [comment]
hi @haruelrovix ,

i use npm.

please install mocha globally 
- npm install mocha -g 
- npm test

**Comment by haruelrovix** [comment]
Thanks for the quick response @sudoak !

Is there any workaround if I don't want to install mocha globally?

**Comment by sudoak** [comment]
@haruelrovix pleasure.

I have done the fix, u need not install mocha globally

**Comment by sudoak** [comment]
@haruelrovix if you need any further changes and updation, feel free to revert.
